// configure, which writes a header of definitions and a hash of what went into it.

#include "commands.h"

#include "utils/utils.h"

#include <fstream>
#include <iomanip>
#include <iostream>
#include <sstream>

#include <stdcorelib/console.h>
#include <stdcorelib/path.h>
#include <stdcorelib/str.h>
#include <stdcorelib/stlextra/algorithms.h>

#include "utils/sha-256.h"

using stdc::u8printf;

int cmd_configure(const cli::ParseResult &result) {
    bool dryrun = isDryRunSet(result);
    bool force = isForceSet(result);
    bool verbose = dryrun || isVerboseSet(result);

    const auto &projectName = result.valueForOption<std::string>("-p").value_or(std::string());
    const auto &fileName = fs::absolute(str2tstr(result.value<std::string>(0).value_or(std::string())));

    // Warning file
    std::vector<std::string> warningLines;
    if (const auto &warningResult = result.option("-w"); warningResult) {
        do {
            const auto &warningFileString =
                warningResult->value<std::string>(0).value_or(std::string());
            if (warningFileString.empty())
                break;

            const auto &warningFile = str2tstr(warningFileString);
            std::ifstream inFile((fs::path(warningFile)));
            if (!inFile.is_open()) {
                break;
            }

            std::string line;
            while (std::getline(inFile, line)) {
                line = stdc::str::trim(std::move(line));
                if (line.empty())
                    continue;
                warningLines.push_back(line);
            }

            inFile.close();
        } while (false);

        if (warningLines.empty()) {
            warningLines = {
                "Caution: This file is generated by CMake automatically during configure.",
                "WARNING!!! DO NOT EDIT THIS FILE MANUALLY!!!",
                "ALL YOUR MODIFICATIONS HERE WILL GET LOST AFTER RE-CONFIGURING!!!",
            };
        }
    }

    // Add defines
    const std::vector<std::string> defines = optionValues(result, "-D");

    // Generate definitions content
    std::string definitions;
    {
        std::map<std::string, size_t> definitionMap;
        std::vector<std::pair<std::string, std::string>> definitionSequence; // Preserve order
        for (const auto &def : std::as_const(defines)) {
            // Raw line
            if (def.front() == '%') {
                definitionSequence.push_back(std::make_pair("%", def.substr(1)));
                continue;
            }

            std::string key;
            std::string val;
            size_t pos = def.find('=');
            if (pos == std::string::npos) {
                key = def;
            } else {
                key = def.substr(0, pos);
                val = def.substr(pos + 1);
            }

            auto it = definitionMap.find(key);
            if (it == definitionMap.end()) {
                definitionMap[key] = definitionSequence.size();
                definitionSequence.push_back(std::make_pair(key, val));
            } else {
                definitionSequence[it->second].second = val;
            }
        }

        std::stringstream ss;
        for (const auto &pair : std::as_const(definitionSequence)) {
            if (pair.first == "%") {
                ss << pair.second << "\n";
            } else if (pair.second.empty()) {
                ss << "#define " << pair.first << "\n";
            } else {
                ss << "#define " << pair.first << " " << pair.second << "\n";
            }
        }
        definitions = ss.str();
    }

    // Calculate hash
    std::string hash;
    if (!force) {
        uint8_t buf[32];
        calc_sha_256(buf, definitions.data(), definitions.size());

        std::stringstream ss;
        ss << std::hex << std::setfill('0');
        for (auto byte : buf) {
            ss << std::setw(2) << static_cast<int>(byte);
        }
        hash = ss.str();
    }

    // Generate content
    std::string content;
    {
        std::string guard = tstr2str(fileName.filename());
        {
            // Prepend project name
            if (!projectName.empty()) {
                guard = projectName + "_" + guard;
            }

            // Replace punctuation signs
            std::replace_if(
                guard.begin(), guard.end(), [](const char &c) { return !isalnum(c) && c != '_'; },
                '_');

            // Macro token can not start with a number, fix it
            if (std::isdigit(guard.front())) {
                guard = "_" + guard;
            }

            // To upper case
            guard = stdc::str::to_upper(guard);
        }

        std::stringstream ss;

        // Header guard
        ss << "#ifndef " << guard << "\n";
        ss << "#define " << guard << "\n\n";

        // Warning
        if (!warningLines.empty()) {
            for (const auto &item : std::as_const(warningLines)) {
                ss << "// " << item << "\n";
            }
            ss << "\n";
        }

        // Hash
        if (!hash.empty()) {
            ss << "// SHA256: " << hash << "\n\n";
        }

        // Definitions
        ss << definitions << "\n";

        // Header guard end
        ss << "#endif // " << guard << "\n";

        content = ss.str();
    }

    if (dryrun) {
        u8printf("%s", content.data());
        return 0;
    }

    // Read file
    do {
        if (force)
            break;

        // Check if file exists and has the same hash
        std::ifstream inFile(fileName);
        if (!inFile.is_open()) {
            break;
        }

        bool matched = false;

        static std::regex hashPattern(R"(^// SHA256: (\w+)$)");
        std::smatch match;
        std::string line;

        int pp_cnt = 0;
        while (std::getline(inFile, line)) {
            if (line.empty())
                continue;

            if (line.front() == '#') {
                pp_cnt++; // Skip header guard
                if (pp_cnt > 2) {
                    break;
                }
                continue;
            }

            if (!stdc::str::starts_with(line, "//"))
                break;

            if (std::regex_match(line, match, hashPattern)) {
                if (match[1] == hash) {
                    matched = true;
                }
                break;
            }
        }
        inFile.close();

        if (matched) {
            if (verbose) {
                stdc::console::printf(stdc::console::bold, stdc::console::yellow,
                                      stdc::console::nocolor, "Content matched. (%s)\n",
                                      hash.data());
            }
            // Same hash found, no need to overwrite the file
            return 0;
        }
    } while (false);

    // Create file
    {
        // Create directory if needed
        if (auto dir = fileName.parent_path(); !fs::is_directory(dir)) {
            fs::create_directories(dir);
        }

        std::ofstream outFile(fileName);
        if (!outFile.is_open()) {
            throw std::runtime_error("failed to open file \"" + tstr2str(fileName) +
                                     "\": " + Utils::standardError());
        }

        outFile << content;
        outFile.close();

        if (verbose) {
            if (!hash.empty()) {
                u8printf("SHA256: %s\n", hash.data());
            }
        }
    }

    return 0;
}

